[package]
name = "wodgen"
version = "0.1.0"
edition = "2021"
authors = ["Taha Hachana <tahahachana@gmail.com>"]

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
csv = "1.3.1"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
chrono = "0.4.38"